set_property SRC_FILE_INFO {cfile:/home/mecaliff/Bureau/4A/S8/PSI/Processeur/Processeur.srcs/constrs_1/new/Test_Freq_Max.xdc rfile:../../../Processeur.srcs/constrs_1/new/Test_Freq_Max.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports CLK]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 } [get_ports RST]
